apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.k3k.io
spec:
  group: k3k.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                version:
                  type: string
                servers:
                  type: integer
                agents:
                  type: integer
                token:
                  type: string
                expose:
                  type: object
                  properties:
                    ingress:
                      type: object
                      properties:
                        enabled: 
                          type: boolean
                        ingressClassName:
                          type: string
                    loadbalancer:
                      type: object
                      properties:
                        enabled: 
                          type: boolean
  scope: Namespaced
  names:
    plural: clusters
    singular: cluster
    kind: Cluster