apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3k-controller
  namespace: k3k-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: k3k-controller
  template:
    metadata:
      labels:
        k8s-app: k3k-controller
      name: k3k-controller
    spec:
      containers:
        - image: husseingalal/k3k:dev
          imagePullPolicy: Always
          name: k3k-controller
          ports:
          - containerPort: 8080
            name: https
            protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: k3k-serviceaccount
      serviceAccountName: k3k-serviceaccount
